version: '3'
services:
  hubbot:
    image: hubbeking/hubbot
    container_name: hubbot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.toml:/app/hubbot.toml
